solr:
  image:
   repository: solr
   tag: 8
  replicaCount: 1
  volumeClaimTemplates:
    storageSize: 5Gi

zookeeper:
  replicaCount: 1
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

mysql:
  enabled: true
  mysqlDatabase: ngao
  mysqlPassword: b0f2b15c9
  mysqlRootPassword: b0f2b15c9
  mysqlUser: ngao
  initializationFiles: {
    grant.sql: GRANT ALL PRIVILEGES ON * . * TO 'ngao'@'%';
  }
  persistence:
    enabled: true
    size: 5Gi

web:
  replicas: 2

rails:
  image:
    repository: registry.gitlab.com/notch8/ngao
    tag: latest
  imagePullPolicy: Always
  imagePullSecrets:
    - name: gitlab
  shared:
    storage:
      size: 5Gi
      className: aws-efs 

ingress:
  # tlsSecretName:
  host: staging-ngao-web.notch8.cloud
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  }

nameOverride:
  ngao

env:
  configmap: 
    NAME: ngao
    RAILS_LOG_TO_STDOUT: true
    MYSQL_ROOT_PASSWORD: ngao
    MYSQL_DATABASE: ngao
    MYSQL_USER: ngao
    IN_DOCKER: "true"
    PASSENGER_APP_ENV: production
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
    SOLR_CONFIGSET_SOURCE_PATH: solr/conf
    SOLR_CONFIGSET: ngao
    SOLR_CORE: ngao

  secret:
    SECRET_KEY_BASE: 88810133e9ec81242e6ce3f277943b2ce23db6bed794e5a697f10ba7bcbdfe7f07e2fb0f2b15c91761d85da912a4faaccabfd7e0e30f3de1163ff247a20db858
    MYSQL_PASSWORD: b0f2b15c9

