# Place any default configuration for solr_wrapper here
version: 8.8.2
download_dir: tmp
instance_dir: tmp/solr_instance
# port: 8983
collection:
  dir: solr/conf/
  name: blacklight-core
  persist: true
