---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.web.name" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
      component: web
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
        component: web
      annotations:
        checksum/rails-env-cm: {{ include (print $.Template.BasePath "/rails-env-cm.yaml") . | sha256sum }}
        checksum/rails-env-secret: {{ include (print $.Template.BasePath "/rails-env-secret.yaml") . | sha256sum }}
    spec:
      restartPolicy: Always
      {{- if .Values.rails.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.rails.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: {{ template "app.rails-env.name" . }}-shared
      initContainers:
        - name: check-solr-ready
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          command: ["/bin/bash"]
          args:
            - "-l"
            - "-c"
            - "response=0 && until [ $response == 200 ]; do response=$(curl --write-out %{http_code} --silent --output /dev/null $(echo $SOLR_BASE_URL)/admin/collections?action=LIST); echo Response is $response; sleep 5; done;"
          envFrom:
            - configMapRef:
                name: {{ template "app.rails-env.name" . }}
        - name: setup
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          volumeMounts:
            - mountPath: /home/app/webapp/public/assets
              name: shared
              subPath: assets
          command: ["/bin/bash"]
          args:
            - "-l"
            - "-c"
            - "(bundle check || bundle install) && bundle exec rails db:create db:migrate && ruby ./chart/bin/solr-setup.rb && bundle exec rake assets:precompile && bundle exec rails db:seed && exit 0"
          envFrom:
            - configMapRef:
                name: {{ template "app.rails-env.name" . }}
            - secretRef:
                name: {{ template "app.rails-env.name" . }}
      containers:
        - name: web
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}
          imagePullPolicy: {{ .Values.rails.imagePullPolicy }}
          # Use sub-path for individual folders
          volumeMounts:
            - mountPath: /home/app/webapp/public/assets
              name: shared
              subPath: assets
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 120
          envFrom:
            - configMapRef:
                name: {{ template "app.rails-env.name" . }}
            - secretRef:
                name: {{ template "app.rails-env.name" . }}
