lilly:
  campus: 'US-InU'
  name: 'Lilly Library'
  visit_note: ''
  description: 'The Lilly Library is the rare books, manuscripts, and special collections library of the Indiana University Libraries, Bloomington. Its collections represent a diversity of subjects, including literature; children’s literature; history; folklore; science; radio, film and television; book collecting and bookselling; journalism; and translation.'
  building: ''
  address1: '1200 East Seventh Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-5500'
  country: 'USA'
  phone: '(812) 855-2452'
  contact_info: 'liblilly@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/iu_feature/Lilly%20Library.exteror.web_.jpg'
  repo_inst_url: 'https://libraries.indiana.edu/lilly-library'
  request_types:
    aeon_web_ead:
      request_url: 'https://sample.request.com'
      request_mappings: 'Action=10&Form=31&Value=ead_url'
wyliehouse:
  campus: 'US-InU'
  name: 'Wylie House Museum'
  visit_note: ''
  description: 'Built in 1835 by Indiana University’s first president, Wylie House Museum is now part of the IU Libraries and is open to the public for guided tours. A rich archival collection contains thousands of Wylie letters that span more than a century, hundreds of photographs, and ephemera.'
  building: ''
  address1: '317 E. 2nd Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47401'
  country: 'United States'
  phone: '812-855-6224'
  contact_info: 'libwylie@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/wylie-house-spring.jpg'
  repo_inst_url: 'https://libraries.indiana.edu/wylie-house-museum'
wmi:
  campus: 'US-InU'
  name: 'Working Men’s Institute'
  visit_note: ''
  description: 'Established by philanthropist William Maclure in 1838, the Working Men’s Institute (WMI) is devoted to the dissemination of useful knowledge. The WMI’s Branigin Archive houses manuscripts and artifacts from New Harmony’s two communal societies (Harmonist and Owenite) and the after glow period (1825-1890) when New Harmony was known as the Athens on the Wabash.'
  building: ''
  address1: ''
  address2: ''
  city: 'New Harmony'
  state: 'IN'
  zip: ''
  country: 'United States'
  phone: ''
  contact_info: 'archivist@workingmensinstitute.org'
  thumbnail_url: 'https://workingmensinstitute.org/wp-content/uploads/2018/03/museum-lg.png'
  repo_inst_url: 'http://www.workingmensinstitute.org/'
archives:
  campus: 'US-InU'
  name: 'University Archives'
  visit_note: ''
  description: 'The Indiana University Archives is the largest and most comprehensive source of information on the history and culture of IU. This site includes finding aids for the records of university and campus organizations as well as the personal papers of IU faculty, staff, and alumni.'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
africanstudies:
  campus: 'US-InU'
  name: 'African Studies Collection'
  visit_note: ''
  description: 'African Studies Collection'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
iuse:
  campus: 'US-InU-Se'
  name: 'Archives and Special Collections, Indiana University Southeast'
  visit_note: ''
  description: 'Archives and Special Collections, Indiana University Southeast'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
aaamc:
  campus: 'US-InU'
  name: 'Archives of African American Music and Culture'
  visit_note: ''
  description: 'Archives of African American Music and Culture'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
atm:
  campus: 'US-InU'
  name: 'Archives of Traditional Music'
  visit_note: ''
  description: 'Archives of Traditional Music'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
bfca:
  campus: 'US-InU'
  name: 'Black Film Center/Archive'
  visit_note: ''
  description: 'Black Film Center/Archive'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
cshm:
  campus: 'US-InU'
  name: 'Center for Documentary Research and Practice'
  visit_note: ''
  description: 'Center for Documentary Research and Practice'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
ewv:
  campus: 'US-InU'
  name: 'Erminie Wheeler-Voegelin Archives'
  visit_note: ''
  description: 'Erminie Wheeler-Voegelin Archives'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
folklore:
  campus: 'US-InU'
  name: 'Folklore Collection'
  visit_note: ''
  description: 'Folklore Collection'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
gimms:
  campus: 'US-InU'
  name: 'Government Information, Maps, & Microform Services'
  visit_note: ''
  description: 'Government Information, Maps, & Microform Services'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
iueast:
  campus: 'US-inrmiue'
  name: 'Indiana University East Archives'
  visit_note: ''
  description: 'Indiana University East Archives'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
music:
  campus: 'US-InU'
  name: 'Indiana University Jacobs School of Music'
  visit_note: ''
  description: 'Indiana University Jacobs School of Music'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
iukokomo:
  campus: 'US-InU-K'
  name: 'Indiana University Kokomo Campus Archives'
  visit_note: ''
  description: 'Indiana University Kokomo Campus Archives'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
iusb:
  campus: 'US-InU-Sb'
  name: 'Indiana University South Bend Archives and Special Collections'
  visit_note: ''
  description: 'Indiana University South Bend Archives and Special Collections'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'http://webapp1.dlib.indiana.edu/archivesOnline/repositoryImages/southeast.jpg'
  repo_inst_url: 'https://library.iusb.edu/search-find/archives/index.html'
iulmia:
  campus: 'US-InU'
  name: 'IU Libraries Moving Image Archive'
  visit_note: ''
  description: 'IU Libraries Moving Image Archive'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
lamc:
  campus: 'US-InU'
  name: 'Latin American Music Center'
  visit_note: ''
  description: 'Latin American Music Center'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
lcp:
  campus: 'US-InU'
  name: 'Liberian Collections'
  visit_note: ''
  description: 'Liberian Collections'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
politicalpapers:
  campus: 'US-InU'
  name: 'Modern Political Papers Collection'
  visit_note: ''
  description: 'Modern Political Papers Collection'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
paleontology:
  campus: 'US-InU'
  name: 'Paleontology Collection'
  visit_note: ''
  description: 'Paleontology Collection'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
ruthlillymedical:
  campus: 'US-iniu'
  name: 'Ruth Lilly Medical Library'
  visit_note: ''
  description: 'Ruth Lilly Medical Library'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
  repo_inst_url: 'http://www.libraries.iub.edu/archives'
kinsey:
  campus: 'US-InU'
  name: 'The Kinsey Institute for Research in Sex, Gender and Reproduction'
  visit_note: ''
  description: 'The Kinsey Institute for Research in Sex, Gender and Reproduction'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'
mediaschool:
  campus: 'US-InU'
  name: 'The Media School Archive'
  visit_note: ''
  description: 'The Media School Archive'
  building: ''
  address1: '1320 East Tenth Street'
  address2: ''
  city: 'Bloomington'
  state: 'IN'
  zip: '47405-7000'
  country: 'United States'
  phone: '812-855-1127'
  contact_info: 'archives@indiana.edu'
  thumbnail_url: 'https://libraries.indiana.edu/sites/default/files/styles/iu_one_third_standard/public/LARGE_archives.jpg?itok=yM3aAt4l'